# Generated by Django 6.0.6 on 2026-06-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('birth_date', models.DateField()),
                ('type', models.CharField(choices=[('a', 'Actor'), ('d', 'Director'), ('p', 'Producer')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('a', 'Action'), ('c', 'Comedy'), ('d', 'Drama'), ('h', 'Horror'), ('s', 'Sci-Fi')], max_length=1)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='core.studio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_people', to='core.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_movies', to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
