# Generated by Django 6.0.6 on 2026-07-02 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_movie_movieperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='liked',
            field=models.CharField(choices=[('l', 'Love'), ('y', 'Yes'), ('n', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
